version: "0.1"
services:

  coolqbot:
    image: he0119/coolqbot:latest
    container_name: coolqbot
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - VNC_PASSWD=Wangzixi
      - COOLQ_ACCOUNT=2089883591
      - COOLQ_URL=https://dlsec.cqp.me/cqp-full
    volumes:
      - ./coolq:/home/user/coolq
      - ./bot:/home/user/coolqbot/bot