services:
  coolqbot:
    container_name: coolqbot
    environment:
    - VNC_PASSWD=Wangzixi
    - COOLQ_URL=https://dlsec.cqp.me/cqa-tuling
    - CQHTTP_USE_WS_REVERSE=yes
    - CQHTTP_WS_REVERSE_API_URL=ws://172.17.0.1:9002/ws/api/
    - CQHTTP_WS_REVERSE_EVENT_URL=ws://172.17.0.1:9002/ws/event/
    - CQHTTP_SHOW_LOG_CONSOLE=no
    - CQHTTP_USE_HTTP=no
    - CQHTTP_USE_WS=no
    image: richardchien/cqhttp:latest
    ports:
    - 9001:9000
    restart: always
    volumes:
    - ./coolq:/home/user/coolq
version: '0.2'
